### ISSUE TITLE
ERROR: OMETIFF can't be installed because it has no versions that support 0.5.1 of julia. 

### ISSUE THREAD

**Issue by coolsecu** [tlnagy/OMETIFF.jl#11]
how to install OMETIFF with Julia 0.5.1?

Thanks

**Comment by tlnagy** [comment]
I have no plans to support 0.5 at this time, sorry.

**Comment by coolsecu** [comment]
Thank you for your message! I moved to 0.6 now.

发自我的 iPhone

在 2017年10月12日，00:34，Tamas Nagy <notifications@github.com<mailto:notifications@github.com>> 写道：


I have no plans to support 0.5 at this time, sorry.

**Comment by tlnagy** [comment]
I hope you find it useful!
