### ISSUE TITLE
Something up with MicroManager OMEs?

### ISSUE THREAD

**Issue by rsrock** [tlnagy/OMETIFF.jl#16]
I'm debugging some code involving reading MicroManager OME files, and I think I stumbled on something weird here. If I open the test image `singles/background_1_MMStack.ome.tif` using this package, you'll see that it's transposed.  However, other ome.tiff images are not transposed.  For example, the neutrophil image is correct.

Do you know if there is something funny about MicroManager files?

[edit] Sure enough, if I add that file to the ""TIFF value verifications" test block, that test fails.

**Comment by tlnagy** [comment]
Yeah, I had noticed that I had to transpose the data with the micromanager files (e.g. the neutrophil one), but not with the simpler tiffs (everything else). I wasn't able to track down what was different about them. I ended up just transposing everything by default till I figure it out

I think the offending line is here:

https://github.com/tlnagy/OMETIFF.jl/blob/10586a0156300f4ac3c09549df18160a6efbce65/src/loader.jl#L88

It's a nasty hack and something that I want to fix.
