### ISSUE TITLE
ERROR: OMETIFF can't be installed because it has no versions that support 0.5.2 of julia

### ISSUE THREAD

**Issue by dns43** [tlnagy/OMETIFF.jl#25]
This issue was already opened 2 years ago, but I wonder if there's any update or workaround to get OMETIFF running under Julia 0.5.2 ?

**Comment by tlnagy** [comment]
Julia 0.5 is unmaintained for more [than a year now](https://discourse.julialang.org/t/julia-0-5-is-now-officially-unmaintained/8169) and I do not plan to support it. You should be able to install OMETIFF.jl v0.1.2 on julia v0.6.x if you don't have access to julia 1.x, but I highly recommend switching to the 1.x branches if you plan to rely on OMETIFF.jl.
