### ISSUE TITLE
Suitable for general use on TIFFs?

### ISSUE THREAD

**Issue by ianshmean** [tlnagy/OMETIFF.jl#56]
I've been trying out putting together an [ImageIO](https://github.com/ianshmean/ImageIO.jl) package, to collect some lower-level, hopefully faster, image IO approaches to potentially allow moving away from ImageMagick. 

Would using this package be appropriate for general TIFFs?

I've currently clang-wrapped LibTIFF (and LibPNG, LibTurboJpeg) and was planning on going that route, unless you think this is well suited and should just be a dep?

I noted this has been developed for accuracy (which I think is great for TIFFs in particular), but it is also faster than say, ImageMagick? (Package and image load times?)

**Comment by tlnagy** [comment]
I haven't benchmarked it extensively against libtiff or ImageMagick.jl (did you get a chance to?), but I was planning to extract out the general TIFF capabilities into a new package. I'm tracking progress here: https://github.com/tlnagy/OMETIFF.jl/issues/12#issuecomment-568213110. 

For feasibility, I don't think getting baseline TIFF support would be that much work, but TIFF has a lot of edge cases which might take a bit to hammer out. How's that sound?

**Comment by ianshmean** [comment]
Sounds great. I've not benchmarked OMETIFF yet.

By the way, what seems to make more sense than ImageIO.jl is to directly point FileIO.jl to TIFF.jl in the same way OMETIFF is linked i.e. https://github.com/JuliaIO/FileIO.jl/blob/bf5577f9d39a0ff9551227e995207da5c77b4e04/src/registry.jl#L254

I'll watch #12 👍🏻

**Comment by tlnagy** [comment]
Going forward https://github.com/tlnagy/TIFF.jl/issues/1 is the issue to track
