### ISSUE TITLE
reduce package size

### ISSUE THREAD

**Issue by johnnychen94** [tlnagy/OMETIFF.jl#87]
It turns out that test images take a lot of space and make a lot of bandwidth spent when `]add OMETIFF` for normal users.

```console
$ du -sh *
 16K	docs
4.0K	LICENSE.md
4.0K	Project.toml
8.0K	README.md
 44K	src
132M	test
```

Maybe upload them to https://github.com/tlnagy/exampletiffs?

**Comment by tlnagy** [comment]
This is a good idea, probably worth purging the files from git history too.

**Comment by johnnychen94** [comment]
> probably worth purging the files from git history too.

The Julia pkg server doesn't serve the entire git history so it is not a must. Purging the files from git history only affects git operations.

**Comment by johnnychen94** [comment]
much smaller :tada:
```julia
$du -sh /Users/jc/.julia/packages/OMETIFF/Wq32Q/*
 16K	/Users/jc/.julia/packages/OMETIFF/Wq32Q/docs
4.0K	/Users/jc/.julia/packages/OMETIFF/Wq32Q/LICENSE.md
4.0K	/Users/jc/.julia/packages/OMETIFF/Wq32Q/Project.toml
8.0K	/Users/jc/.julia/packages/OMETIFF/Wq32Q/README.md
 44K	/Users/jc/.julia/packages/OMETIFF/Wq32Q/src
1.1M	/Users/jc/.julia/packages/OMETIFF/Wq32Q/test
```
